package com.mobilewe.wemobile.resources.strings

interface IStringResources {
    val yourAddress: String
    val invalidAddress: String
    val unknownError: String
    val wifiDisabled: String
    val requestFailed: String
    val noInternet: String
    val invalidPhoneNumber: String
    val invalidEmail: String
    val invalidFullName: String
    val oppsRegistrationNotCompleted: String
    val beepBeep: String
    val backgroundDescription: String
    val loginWelcomeMessage: String
    val loginSubWelcomeMessage: String
    val usernameLabel: String
    val passwordLabel: String
    val confirmPasswordLabel: String
    val login: String
    val keepMeLoggedIn: String
    val signUpNow: String
    val signUpDescription: String
    val home: String
    val search: String
    val orders: String
    val notification: String
    val profile: String
    val wallet: String
    val welcome: String
    val searchHint: String
    val invalidUsername: String
    val invalidPassword: String
    val languageAskAboutLanguage: String
    val selectLanguage: String
    val joinBpToday: String
    val createYourAccount: String
    val next: String
    val justOnMoreStep: String
    val completeYourRegistration: String
    val fullName: String
    val email: String
    val mobileNumber: String
    val signUp: String
    val username: String
    val password: String
    val ridePreferredTitle: String
    val ridePreferredSubTitle: String
    val today: String
    val thisWeek: String
    val address: String
    val pleaseLogin: String
    val mostOrdered: String
    val sweets: String
    val free: String
    val loginToAddToFavourite: String
    val addToCart: String
    val mealAddedToYourCart: String
    val mealFailedToAddInCart: String
    val message: String
    val supportTeam: String
    val sendMessageToStartLiveChat: String
    val greetings: String
    val paySomeone : String
    val paySomeoneDesc: String
    val requestMoney: String
    val requestMoneyDesc: String
    val buyAirtime: String
    val buyAirtimeDesc: String
    val payBillAndBuyGoods: String
    val payBillDescr: String
    val payBillTitle: String
    val buyGoodsTitle: String
}
