package com.mobilewe.wemobile.resources.strings

interface IStringResources {
    val yourAddress: String
    val invalidAddress: String
    val unknownError: String
    val wifiDisabled: String
    val requestFailed: String
    val noInternet: String
    val invalidPhoneNumber: String
    val invalidEmail: String
    val invalidFullName: String
    val oppsRegistrationNotCompleted: String
    val beepBeep: String
    val backgroundDescription: String
    val loginWelcomeMessage: String
    val loginSubWelcomeMessage: String
    val usernameLabel: String
    val passwordLabel: String
    val confirmPasswordLabel: String
    val login: String
    val keepMeLoggedIn: String
    val signUpNow: String
    val signUpDescription: String
    val home: String
    val search: String
    val orders: String
    val notification: String
    val profile: String
    val wallet: String
    val welcome: String
    val searchHint: String
    val invalidUsername: String
    val invalidPassword: String
    val languageAskAboutLanguage: String
    val selectLanguage: String
    val joinBpToday: String
    val createYourAccount: String
    val next: String
    val justOnMoreStep: String
    val completeYourRegistration: String
    val fullName: String
    val email: String
    val mobileNumber: String
    val signUp: String
    val username: String
    val password: String
    val ridePreferredTitle: String
    val ridePreferredSubTitle: String
    val today: String
    val thisWeek: String
    val address: String
    val pleaseLogin: String
    val mostOrdered: String
    val sweets: String
    val free: String
    val loginToAddToFavourite: String
    val addToCart: String
    val mealAddedToYourCart: String
    val mealFailedToAddInCart: String
    val message: String
    val supportTeam: String
    val sendMessageToStartLiveChat: String
    val greetings: String
    val paySomeone : String
    val paySomeoneDesc: String
    val requestMoney: String
    val requestMoneyDesc: String
    val buyAirtime: String
    val buyAirtimeDesc: String
    val payBillAndBuyGoods: String
    val payBillDescr: String
    val payBillTitle: String
    val buyGoodsTitle: String
    val passwordVisibleContentDescription: String
    val passwordHiddenContentDescription: String
    val payBillNumber: String
    val accountNumber: String
    val payBillAmount: String
    val pinHint: String
    val confirmPin: String
    val currentPin: String
    val newPin: String
    val confirmNewPin: String
    val currentPassword: String
    val confirmNewPassword: String
    val newPassword: String
    val transaction: String
    val submit: String
    val userProfile: String
    val amount: String
    val minAmount: String
    val payWithSacco: String
    val helpCenter: String
    val appTheme: String
    val turnOnIncognito: String
    val appLanguage: String
    val settings: String
    val driveMode: String
    val childMode: String
    val timeWatched: String
    val accountData: String
    val rateUsOnPlayStore: String
    val feedback: String
    val forum: String
    val privacyPolicy: String
    val termsOfService: String
    val nightLight: String
    val phoneNumber: String
    val buyAirtimeHomeTitle: String
    val tillNumber: String
    val businessNumber: String
    val deposit: String
    val withdraw: String
    val paybill: String
    val buygoods: String
    val buyGoods: String
    val sendMoneyUnderscore: String
    val savings: String
    val ourMarket: String
    val loan: String
    val billPayAndTillPayHint: String
    val busTravelHint: String
    val flightHint: String
    val trainHint: String
    val hotelHint: String
    val schedulePayment: String
    val addFavourite: String
    val favorite: String
    val ownEquityAccount: String
    val anotherEquityAccount: String
    val payTopUp: String
    val creditPrepaid: String
    val mobileWallet: String
    val sendToMobile: String
    val anotherBank: String
    val payBill: String
    val withdrawHint: String
    val promptInfoTitle: String
    val promptInfoSubtitle: String
    val promptInfoDescription: String
    val promptInfoUseAppPassword: String
    val continuee: String
    val saccoApp: String
    val loanStatement: String
    val requestLoan: String
    val payLoan: String
    val recentTransaction: String
    val dontHaveAnAccount: String
    val alreadyHaveAnAccount: String
    val yourBalance: String
    val checkAllTransaction: String
    val managePin: String
    val checkSaccoStatement: String
    val electronics: String
    val loanBalance: String
    val limit: String
    val dueDate: String
    val signIn: String
    val emailOrMobileNumber: String
    val emailHint: String
    val userRegisterNamesHint: String
    val mobileNumberHint: String
    val idNumberHint: String
    val helloBlankFragment: String
    val enterPin: String
    val account: String
    val shopHeaderText: String
    val amountSupportText: String
    val transactionDetail: String
    val recipientNo: String
    val date: String
    val moneyIn: String
    val moneyOut: String
    val moneyBalance: String
    val transactionType: String
    val totalAmount: String
    val availableBalance: String
    val statement: String
    val onboardingOneTitle: String
    val onboardingOneDescription: String
    val onboardingTwoTitle: String
    val onboardingTwoDescription: String
    val onboardingThreeTitle: String
    val onboardingThreeDescription: String
    val welcomeToSacco: String
    val welcomeTitleOne: String
    val welcomeSubOne: String
    val welcomeTitleTwo: String
    val welcomeTitleThree: String
    val welcomeSubTwo: String
    val introFeatureOneTitle: String
    val introFeatureOneDesc: String
    val introFeatureTwoTitle: String
    val introFeatureTwoDesc: String
    val introFeatureThreeTitle: String
    val introFeatureThreeDesc: String
    val exploreBtnText: String
    val continueWithGoogle: String
    val saccoPrivacyPolicy: String
    val saccoTermsAndConditions: String
    val saccoServiceCharter: String
    val seeAll: String
    val bankTransfer: String
    val recipientProvider: String
    val accountType: String
    val allRecipientWithEmoji: String
    val pin: String
    val enterYourLoan: String
    val apply: String
    val selectFinishDateTitle: String
    val notFoundEmail: String
    val copyToClipboard: String
    val openAccount: String
    val goalSaving: String
    val fixedSaving: String
    val targetSavings: String
    val goalSavingsDescription: String
    val passwordHint: String
    val reEnterPasswordHint: String
    val createPassword: String
    val createPasswordHeader: String
    val createPasswordHint: String
    val confirmPassword: String
    val passwordTitle: String
    val validateHeader: String
    val validateLetter: String
    val validateCharLong: String
    val validateSpecialChar: String
    val passwordMatch: String
    val pinValidateHeader: String
    val validateSequence: String
    val validateRepetitive: String
    val verifyHeader: String
    val aboutSaccoRide: String
    val termsAndConditions: String
    val serviceCharter: String
    val logout: String
    val share: String
    val save: String

}
