package com.mobilewe.wemobile.resources.strings.sw

import com.mobilewe.wemobile.resources.strings.IStringResources


data class Swahili(
    override val beepBeep: String = "WesaccoMobile",
    override val backgroundDescription: String = "background image",
    override val loginWelcomeMessage: String = "Karibu kwenye programu ya Beep Beep",
    override val loginSubWelcomeMessage: String = "Ingia ili kupata huduma zote",
    override val usernameLabel: String = "Jina la mtumiaji",
    override val passwordLabel: String = "Nenosiri",
    override val login: String = "Ingia",
    override val keepMeLoggedIn: String = "Nisalie nimeingia",
    override val signUpNow: String = "Jiunge sasa",
    override val signUpDescription: String = "Huna akaunti?",
    override val home: String = "Mwanzo",
    override val search: String = "Tafuta",
    override val orders: String = "Oda",
    override val notification: String = "Arifa",
    override val profile: String = "Profaili",
    override val wallet: String = "Mkoba",
    override val welcome: String = "Karibu",
    override val searchHint: String = "Tafuta chakula, mgahawa",
    override val invalidUsername: String = "Jina la mtumiaji si sahihi",
    override val languageAskAboutLanguage: String = "Unazungumza lugha gani?",
    override val selectLanguage: String = "Chagua lugha yako.",
    override val joinBpToday: String = "Jiunge na Beep Beep Leo!",
    override val createYourAccount: String = "Tengeneza akaunti yako",
    override val next: String = "Ifuatayo",
    override val justOnMoreStep: String = "Hatua moja tu zaidi!",
    override val completeYourRegistration: String = "Kamilisha usajili wako",
    override val fullName: String = "Jina kamili",
    override val email: String = "Barua pepe",
    override val mobileNumber: String = "Nambari ya simu",
    override val signUp: String = "Jiunge",
    override val username: String = "Jina la mtumiaji",
    override val password: String = "Nenosiri",
    override val ridePreferredTitle: String = "Unapendelea nini kwa safari zako za teksi?",
    override val ridePreferredSubTitle: String = "Tusaidie kuboresha uzoefu wako nasi.",
    override val today: String = "Leo",
    override val thisWeek: String = "Wiki Hii",
    override val invalidPassword: String = "Nenosiri si sahihi",
    override val unknownError: String = "Hitilafu isiyojulikana",
    override val wifiDisabled: String = "WIFI imezimwa",
    override val requestFailed: String = "Ombi limeshindwa",
    override val noInternet: String = "Hakuna Intaneti",
    override val invalidPhoneNumber: String = "Nambari ya simu si sahihi",
    override val invalidEmail: String = "Barua pepe si sahihi",
    override val invalidFullName: String = "Jina kamili si sahihi",
    override val oppsRegistrationNotCompleted: String = "Ooops, Usajili haujakamilika",
    override val address: String = "Anwani",
    override val invalidAddress: String = "Anwani si sahihi",
    override val yourAddress: String = "Anwani yako",
    override val mostOrdered: String = "Vilivyowekwa oda zaidi",
    override val sweets: String = "Vyakula vya utamu",
    override val free: String = "Bure",
    override val loginToAddToFavourite: String = "Tafadhali ingia kuongeza",
    override val addToCart: String = "Ongeza kwenye kikapu",
    override val mealAddedToYourCart: String = "Chakula kimeongezwa kwenye kikapu chako",
    override val mealFailedToAddInCart: String = "Hitilafu ilitokea wakati wa kuongeza chakula kwenye kikapu chako",
    override val pleaseLogin: String = "Tafadhali ingia ili kufikia profaili yako",
    override val message: String = "Ujumbe",
    override val supportTeam: String = "Timu ya msaada",
    override val sendMessageToStartLiveChat: String = "Tuma ujumbe kuanza mazungumzo ya moja kwa moja!",
    override val confirmPasswordLabel: String = "Thibitisha Nenosiri",
    override val greetings: String = "Hujambo,",
    override val paySomeone: String = "Lipa mtu",
    override val paySomeoneDesc: String = "Kwa mkoba, benki au nambari ya simu",
    override val requestMoney: String = "Omba pesa",
    override val requestMoneyDesc: String = "Omba pesa kutoka kwa watumiaji wa WeSaccoMobile",
    override val buyAirtime: String = "Nunua muda wa maongezi",
    override val buyAirtimeDesc: String = "Jaza au tuma muda wa maongezi katika mitandao yote",
    override val payBillAndBuyGoods: String = "Lipa bili & nunua bidhaa",
    override val payBillDescr: String = "Simamia bili zako zote na miamala ya wafanyabiashara",
    override val payBillTitle: String = "Lipa Bili",
    override val buyGoodsTitle: String = "Nunua Bidhaa"
) : IStringResources

