package com.mobilewe.wemobile.resources.strings.en

import com.mobilewe.wemobile.resources.strings.IStringResources

data class English(
    override val beepBeep: String = "WesaccoMobile",
    override val backgroundDescription: String = "background image",
    override val loginWelcomeMessage: String = "Welcome To Beep Beep App",
    override val loginSubWelcomeMessage: String = "Login to access all the features",
    override val usernameLabel: String = "Username",
    override val passwordLabel: String = "Password",
    override val login: String = "Login",
    override val keepMeLoggedIn: String = "Keep me logged in",
    override val signUpNow: String = "Sign up now",
    override val signUpDescription: String = "Don't have an account ?",
    override val home: String = "Home",
    override val search: String = "Search",
    override val orders: String = "Orders",
    override val notification: String = "Notification",
    override val profile: String = "Profile",
    override val wallet: String = "Wallet",
    override val welcome: String = "Welcome",
    override val searchHint: String = "Search for meal, restaurant",
    override val invalidUsername: String = "invalid username",
    override val languageAskAboutLanguage: String = "What language do you speak?",
    override val selectLanguage: String = "Pick your language.",
    override val joinBpToday: String = "Join Beep Beep Today!",
    override val createYourAccount: String = "Create your account",
    override val next: String = "Next",
    override val justOnMoreStep: String = "Just one more step!",
    override val completeYourRegistration: String = "Complete your registration",
    override val fullName: String = "Full name",
    override val email: String = "Email",
    override val mobileNumber: String = "Mobile number",
    override val signUp: String = "Sign up",
    override val username: String = "Username",
    override val password: String = "Password",
    override val ridePreferredTitle: String = "Which do you prefer for your taxi rides?",
    override val ridePreferredSubTitle: String = "Help us improve your experience with us.",
    override val today: String = "Today",
    override val thisWeek: String = "This Week",
    override val invalidPassword: String = "Invalid Password",
    override val unknownError: String = "Unknown Error",
    override val wifiDisabled: String = "WIFI Disabled",
    override val requestFailed: String = "Request Failed",
    override val noInternet: String = "No Internet",
    override val invalidPhoneNumber: String = "Invalid Phone Number",
    override val invalidEmail: String = "Invalid Email",
    override val invalidFullName: String = "Invalid Full Name",
    override val oppsRegistrationNotCompleted: String = "Opps, Registration Not Completed",
    override val address: String = "Address",
    override val invalidAddress: String = "Invalid Address",
    override val yourAddress: String = "Your Address",
    override val mostOrdered: String = "Most Ordered",
    override val sweets: String = "Sweets",
    override val free: String = "Free",
    override val loginToAddToFavourite: String = "Please login to add",
    override val addToCart: String = "Add to cart",
    override val mealAddedToYourCart: String = "Meal added to your cart",
    override val mealFailedToAddInCart: String = "error while add Meal to your cart",
    override val pleaseLogin: String = "Please log in to access your profile",
    override val message: String = "Message",
    override val supportTeam: String = "Support team",
    override val sendMessageToStartLiveChat: String = "Send a message to start the live chat!",
    override val confirmPasswordLabel: String = "Confirm Password",
    override val greetings: String = "Hey,",
    override val paySomeone: String = "Pay someone",
    override val paySomeoneDesc: String = "To Wallet bank,or mobile number",
    override val requestMoney: String = "Request money",
    override val requestMoneyDesc: String = "Request money from WeSaccoMobile users",
    override val buyAirtime: String = "Buy airtime",
    override val buyAirtimeDesc: String = "Top-up or send airtime across all network",
    override val payBillAndBuyGoods: String = "Pay bill & buy goods",
    override val payBillDescr: String = "Manage all your bills and merchant transactions",
    override val payBillTitle: String = "Pay Bill",
    override val buyGoodsTitle: String = "Buy Goods",

    ) : IStringResources
